Topics to be covered in this Notebook:

1. Numpy
2. Pandas
3. Exploratory Data Analysis

- Author : Aritra Sen (www.aritrasen.com)
- LinkedIn : https://www.linkedin.com/in/aritrasen/

#### Numpy:

Numpy is the short form of ‘Numerical Python‘. This is one library you should learn if you are interested in Data Science with Python. The core of Numpy is it’s N-Dimension Array which is similar to List but has many advance over List like –

- More compact.
- Faster access in Reading and writing items.
- Ease of doing element wise operation in Numpy.
- Numpy has inbuilt functions to do mathematical operations on arrays.

As we are using Jupyter notebook from Anaconda , Numpy library is already installed in Anaconda. But we need to import the Numpy library. Now lets look into the Numpy array , it’s advantages over list and different available functionalities of Numpy.

In [1]:
#Import the Numpy Library
import numpy as np 

In [2]:
a = np.array([1,2,3]) #Creating an 1-D Numpy Array
print(a)

[1 2 3]


In [3]:
#Arguement list to creare Numpy array 
# np.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

#Creating an 2-D Array 

b = np.array([[1,2,3],[4,5,6]])
print(b)

# Print out the shape of array
print('Shape:' + str(b.shape))

# Shape is a tuple , first is no of rows and secords element is no of columns

# Print out the data type of array
print(b.dtype)

[[1 2 3]
 [4 5 6]]
Shape:(2, 3)
int64


### Comparison between Numpy and List

In [4]:
my_list = [1,2,3]

# To multipl each element of the list with we will need to write loop
emp_list = []
for element in my_list:
    emp_list.append(element*2)
print(emp_list)  

#We can't do straight way elementwise multiplication in list 
my_list*2 #This is do concatenation

[2, 4, 6]


[1, 2, 3, 1, 2, 3]

In [5]:
# However in Numpy Array we can easily do elementwise operation
# Avoiding the slow for loop

a = np.array([1,2,3])
print(a*2) #Much faster way to do

[2 4 6]


### Mathematical Operations using numpy

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print('Add :', a+b) #same as np.add(a,b)
print('Substract: ',a-b) #same as np.substract(a,b)
print ('Multiply: ',np.multiply(a,b))  
print ('Divide: ',np.divide(a,b)) 
print('Square root: ', np.sqrt(a)) #Elementwise square root

Add : [5 7 9]
Substract:  [-3 -3 -3]
Multiply:  [ 4 10 18]
Divide:  [0.25 0.4  0.5 ]
Square root:  [1.         1.41421356 1.73205081]


In [8]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(np.dot(x,y)) #Matrix Product

[[19 22]
 [43 50]]


In [9]:
x = np.array([[1,2],[3,4]])
print(np.transpose(x)) # Matrix Transpose

[[1 3]
 [2 4]]


### Functions to create different types of arrays

In [10]:
a = np.zeros((2,2)) # 2*2 array of zeros , assign the dimensions as you need
print(a)

[[0. 0.]
 [0. 0.]]


In [11]:
b = np.ones((1,2)) # array of all ones
print(b)

[[1. 1.]]


In [12]:
c = np.eye(2) # Creates an 2*2 Identity matrix
print(c)

[[1. 0.]
 [0. 1.]]


In [13]:
d = np.random.random((2,2)) # Creates an array random numbers
print(d)

[[0.5275685  0.30631075]
 [0.73400404 0.57945371]]
